import React, { useState } from "react";
import axios from "axios";
import DropzoneBox from "../components/DropzoneBox";
import "../animations.css";

export default function Home() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleFile = async (file) => {
    if (!file) return;

    const formData = new FormData();
    formData.append("file", file);

    setLoading(true);
    setData(null);

    try {
      const res = await axios.post("http://localhost:5000/api/upload", formData);
      setData(res.data);
    } catch (err) {
      console.error("UPLOAD ERROR:", err);
      alert("Server error. Check backend terminal.");
    }
    setLoading(false);
  };

  const copyText = (text) => navigator.clipboard.writeText(text || "");

  return (
    <div className="min-h-screen bg-gray-100 py-10 px-6">
      <div className="max-w-6xl mx-auto">

        {/* Header + Dropzone */}
        <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-200 mb-10">
          <h1 className="text-3xl md:text-4xl font-extrabold text-center text-gray-900 mb-4">
            Social Media Content Analyzer (AI Enhanced)
          </h1>

          <div className="flex justify-center">
            <DropzoneBox onFileSelected={handleFile} />
          </div>

          {loading && (
            <div className="mt-8 flex flex-col items-center animate-fadeIn">
              <div className="loader mb-3"></div>
              <p className="text-gray-600 text-sm">Processing your file with AI...</p>
            </div>
          )}
        </div>

        {/* Main Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* LEFT SIDE */}
          <div className="lg:col-span-2 space-y-6">

            {/* Extracted Text */}
            <div className="bg-white rounded-2xl p-6 shadow-md border animate-fadeIn">
              <h2 className="text-lg font-bold text-gray-800 mb-3">
                📄 Original Extracted Text
              </h2>

              {!data && (
                <p className="text-gray-400 text-sm">
                  Upload a file to extract text.
                </p>
              )}

              {data &&
                data.original
                  .split(/\n\s*\n/)
                  .map((para, i) => (
                    <p key={i} className="mb-3 whitespace-pre-wrap">
                      {para.trim()}
                    </p>
                  ))}
            </div>

            {/* AI Suggestions (Now BELOW Extracted Text) */}
            <div className="bg-white rounded-2xl p-6 shadow-md border animate-fadeIn">
              <h2 className="text-lg font-bold text-gray-800 mb-3">
                ✨ AI Suggestions
              </h2>

              {!data && (
                <p className="text-gray-400 text-sm">
                  Suggestions will appear here after upload.
                </p>
              )}

              {data &&
                data.suggestions
                  .split(/\n\s*\n/)
                  .map((s, i) => (
                    <div key={i} className="flex gap-3 items-start mb-2">
                      <div className="text-blue-500 font-bold text-lg">•</div>
                      <p className="text-gray-700 whitespace-pre-wrap">{s.trim()}</p>
                    </div>
                  ))}
            </div>

          </div>

          {/* RIGHT SIDE – AI Rewritten */}
          <div className="space-y-6">

            <div className="bg-blue-600 text-white rounded-2xl p-6 shadow-lg animate-fadeIn">
              <h2 className="text-lg font-bold">🤖 AI Rewritten Version</h2>
              <p className="text-sm opacity-80 mb-4">
                Improved, polished output generated by Gemini 2.5.
              </p>

              {!data && (
                <p className="text-white/80 text-sm">
                  AI rewritten version will appear here.
                </p>
              )}

              {data &&
                data.rewritten
                  .split(/\n\s*\n/)
                  .map((para, i) => (
                    <p key={i} className="mb-3 whitespace-pre-wrap">
                      {para.trim()}
                    </p>
                  ))}
            </div>

          </div>

        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-400">
          Powered by Gemini 2.5 Flash • Built with ❤️ by Shubham Singh
        </div>
      </div>
    </div>
  );
}
